name: Pull Request(NPM)

on:
  pull_request:
    branches:
      - master
    paths:
      - "package.json"

permissions:
  pull-requests: write
  contents: write

jobs:
  test-small:
    if: ${{ github.actor == 'dependabot[bot]' }}
    uses: ./.github/workflows/test-small.yml
    secrets:
      CONFIG_ID: ${{ secrets.CONFIG_ID }}
      PAT: ${{ secrets.PAT }}
  test-medium:
    if: ${{ github.actor == 'dependabot[bot]' }}
    uses: ./.github/workflows/test-medium.yml
    secrets:
      CONFIG_ID: ${{ secrets.CONFIG_ID }}
      PAT: ${{ secrets.PAT }}
  auto-merge:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    needs:
      - test-small
      - test-medium
    steps:
      - name: Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v2.2.0
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
      - name: Enable auto-merge for Dependabot PRs
        if: ${{ steps.metadata.outputs.update-type }} == 'version-update:semver-patch' || ${{ steps.metadata.outputs.update-type }} == 'version-update:semver-minor'
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
