name: Test of smoke build

on:
  workflow_call:

jobs:
  test-smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      status: ${{ steps.test.outputs.status }}
    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2
      - name: Download fonts
        run: |
          curl -sSL -O https://github.com/googlefonts/morisawa-biz-ud-gothic/releases/download/v1.051/BIZUDGothic.zip
          unzip BIZUDGothic.zip
      - name: Install dependencies
        run: bun install
      - name: Run test
        id: test
        run: bun run build
        env:
          CONFIG_ID: ${{ secrets.CONFIG_ID }}
          PAT: ${{ secrets.PAT }}