name: Test of small size

on:
  workflow_call:

jobs:
  test-small:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      status: ${{ steps.test.outputs.status }}
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: Run test
        id: test
        run: bun run test:small
        env:
          CONFIG_ID: ${{ secrets.CONFIG_ID }}
          PAT: ${{ secrets.PAT }}