name: Test of small size

on:
  workflow_call:
    secrets:
      CONFIG_ID:
        required: true
      PAT:
        required: true
    outputs:
      status:
        value: ${{ jobs.test-small.outputs.status }}

jobs:
  test-small:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      status: ${{ steps.test.outputs.status }}
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: Run test
        id: test
        run: bun run test:small || echo "status=$?" >> $GITHUB_OUTPUT
        env:
          CONFIG_ID: ${{ secrets.CONFIG_ID }}
          PAT: ${{ secrets.PAT }}