name: Upgrade dependencies for Deno

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * 3"

permissions:
  pull-requests: write
  contents: write

env:
  PR_BRANCH: deno-dependency-updates

jobs:
  update:
    runs-on: ubuntu-latest
    outputs:
      pull-request-url: ${{ steps.cpr.outputs.pull-request-url }}
      pr-exists: ${{ steps.check.outputs.pr_exists }}
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v1.x
      - name: Update dependencies with udd
        id: run-deno-udd
        env:
          NO_COLOR: true
        run: |
          {
            echo 'UDD_RESULT<<EOF'
            deno run --allow-all https://deno.land/x/udd/main.ts deno.json $(find . -maxdepth 0 -type f | grep -E ".*\.([mc]?(ts|js)|(ts|js)x?)$" -) || true
            echo EOF
          } >> $GITHUB_OUTPUT
      - uses: peter-evans/create-pull-request@v7
        id: cpr
        with:
          commit-message: ":arrow_up: Update deno dependencies"
          title: Update Deno dependencies
          body: |-
            Some external modules are stale.
            <details><summary>Details</summary><div>

            ```
            ${{ steps.run-deno-udd.outputs.UDD_RESULT }}
            ```

            </div></details>
          branch: ${{ env.PR_BRANCH }}
          author: github-actions[bot] <noreply@github.com>
          delete-branch: true
      - name: Set Pull Request URL
        run: echo "pull-request-url=${{ steps.cpr.outputs.pull-request-url }}" >> $GITHUB_ENV
      - name: Check if PR exists
        id: check
        run: |
          prs=$(gh pr list \
              --head ${{ env.PR_BRANCH }} \
              --base 'master' \
              --json title \
              --jq 'length')
          if ((prs > 0)); then
              echo "pr_exists=true" >> "$GITHUB_OUTPUT"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  test-medium:
    needs:
      - update
    if: ${{ needs.update.outputs.pr-exists }}
    uses: ./.github/workflows/test-medium.yml
    with:
      ref: deno-dependency-updates
    secrets:
      CONFIG_ID: ${{ secrets.CONFIG_ID }}
      PAT: ${{ secrets.PAT }}
  auto-merge:
    runs-on: ubuntu-latest
    needs:
      - update
      - test-medium
    if: ${{ needs.update.outputs.pr-exists }}
    steps:
      - uses: actions/checkout@v4
      - if: ${{ needs.test-medium.outputs.status != 0 }}
        name: Deny Pull Request
        run:
          gh pr close ${{needs.update.outputs.pull-request-url}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - if: ${{ needs.test-medium.outputs.status == 0 }}
        name: Enable auto-merge
        run: gh pr merge --auto --merge ${{needs.update.outputs.pull-request-url}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Delete branch
        run: git push origin ${{ env.PR_BRANCH }} -d
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}